"""Initial migration with all tables

Revision ID: d357ff4921a5
Revises: 
Create Date: 2025-12-17 11:18:16.755548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Import GUID type from our models
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from app.models.base import GUID


# revision identifiers, used by Alembic.
revision: str = 'd357ff4921a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('industries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_industries_name'), ['name'], unique=True)

    op.create_table('investors',
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='User ID from external authentication system'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Investor or firm name'),
    sa.Column('firm_name', sa.String(length=255), nullable=True, comment='Investment firm/organization name'),
    sa.Column('bio', sa.Text(), nullable=True, comment='Investor bio or description'),
    sa.Column('website', sa.String(length=500), nullable=True, comment='Investor or firm website URL'),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True, comment='LinkedIn profile URL'),
    sa.Column('min_check_size', sa.Numeric(precision=12, scale=2), nullable=True, comment='Minimum investment amount'),
    sa.Column('max_check_size', sa.Numeric(precision=12, scale=2), nullable=True, comment='Maximum investment amount'),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investors_user_id'), ['user_id'], unique=True)

    op.create_table('questions',
    sa.Column('text', sa.Text(), nullable=False, comment='The question text displayed to users'),
    sa.Column('category', sa.Enum('TRACTION', 'TEAM', 'FINANCE', 'MARKET', name='questioncategory'), nullable=False, comment='Primary category: traction, team, finance, or market'),
    sa.Column('answer_type', sa.Enum('NUMBER', 'BOOLEAN', 'ENUM', 'TEXT', name='answertype'), nullable=False, comment='Expected answer format: number, boolean, enum, or text'),
    sa.Column('base_weight', sa.Numeric(precision=5, scale=2), nullable=False, comment='Base scoring weight for this question'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this question is currently active in assessments'),
    sa.Column('help_text', sa.Text(), nullable=True, comment='Additional guidance or explanation for the question'),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_is_active'), ['is_active'], unique=False)

    op.create_table('startups',
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='User ID from external authentication system'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.Enum('IDEA', 'MVP_NO_TRACTION', 'MVP_EARLY_TRACTION', 'GROWTH', 'SCALE', name='startupstage'), nullable=False),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_startups_user_id'), ['user_id'], unique=False)

    op.create_table('assessments',
    sa.Column('startup_id', GUID(length=36), nullable=False),
    sa.Column('stage', sa.Enum('IDEA', 'MVP_NO_TRACTION', 'MVP_EARLY_TRACTION', 'GROWTH', 'SCALE', name='startupstage'), nullable=False),
    sa.Column('framework_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'PUBLISHED', 'ARCHIVED', name='assessmentstatus'), nullable=False),
    sa.Column('computed_score', sa.Integer(), nullable=True),
    sa.Column('score_band', sa.Enum('CRITICAL', 'POOR', 'FAIR', 'GOOD', 'EXCELLENT', name='scoreband'), nullable=True),
    sa.Column('responses', sa.JSON(), nullable=False, comment='KPI responses in format: {kpi_id: {value, evidence_type, evidence_id, answered_at}}'),
    sa.Column('score_metadata', sa.JSON(), nullable=True, comment='Explainability payload: category breakdown, penalties, recommendations'),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calculation_duration_ms', sa.Integer(), nullable=True, comment='Performance tracking'),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index('ix_assessment_score_band', ['score_band', 'computed_score'], unique=False)
        batch_op.create_index('ix_assessment_startup_status', ['startup_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_computed_score'), ['computed_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_startup_id'), ['startup_id'], unique=False)

    op.create_table('investor_preferences',
    sa.Column('investor_id', GUID(length=36), nullable=False),
    sa.Column('industry_id', GUID(length=36), nullable=True, comment='Preferred industry/sector'),
    sa.Column('stage', sa.Enum('IDEA', 'MVP_NO_TRACTION', 'MVP_EARLY_TRACTION', 'GROWTH', 'SCALE', name='startupstage'), nullable=True, comment='Preferred startup stage'),
    sa.Column('ticket_min', sa.Numeric(precision=12, scale=2), nullable=True, comment='Minimum ticket size for this preference'),
    sa.Column('ticket_max', sa.Numeric(precision=12, scale=2), nullable=True, comment='Maximum ticket size for this preference'),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False, comment='Relative importance of this preference (for scoring)'),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investor_preferences', schema=None) as batch_op:
        batch_op.create_index('ix_investor_preferences_industry', ['industry_id'], unique=False)
        batch_op.create_index('ix_investor_preferences_investor', ['investor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investor_preferences_investor_id'), ['investor_id'], unique=False)
        batch_op.create_index('ix_investor_preferences_stage', ['stage'], unique=False)

    op.create_table('question_options',
    sa.Column('question_id', GUID(length=36), nullable=False),
    sa.Column('value', sa.Text(), nullable=False, comment='The option text/value'),
    sa.Column('score_weight', sa.Numeric(precision=5, scale=2), nullable=False, comment='Scoring multiplier for this option'),
    sa.Column('display_order', sa.Integer(), nullable=True, comment='Optional ordering for display'),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_options_question_id'), ['question_id'], unique=False)

    op.create_table('scoring_rules',
    sa.Column('question_id', GUID(length=36), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False, comment='Scoring weight/multiplier for this rule'),
    sa.Column('min_value', sa.Numeric(precision=12, scale=2), nullable=True, comment='Minimum value for range-based scoring (inclusive)'),
    sa.Column('max_value', sa.Numeric(precision=12, scale=2), nullable=True, comment='Maximum value for range-based scoring (inclusive)'),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scoring_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scoring_rules_question_id'), ['question_id'], unique=False)

    op.create_table('startup_investor_matches',
    sa.Column('startup_id', GUID(length=36), nullable=False),
    sa.Column('investor_id', GUID(length=36), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=False, comment='Computed match score (0-100 or normalized 0-1)'),
    sa.Column('match_reason', sa.Text(), nullable=False, comment='Explainability: Why this match was made (for investor transparency)'),
    sa.Column('algorithm_version', sa.String(), nullable=True, comment='Version/ID of matching algorithm used'),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False, comment='Whether this match was manually curated vs algorithmically generated'),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('startup_id', 'investor_id', name='uq_startup_investor_match')
    )
    with op.batch_alter_table('startup_investor_matches', schema=None) as batch_op:
        batch_op.create_index('ix_matches_investor_score', ['investor_id', 'match_score'], unique=False)
        batch_op.create_index('ix_matches_score', ['match_score'], unique=False)
        batch_op.create_index('ix_matches_startup_score', ['startup_id', 'match_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_startup_investor_matches_investor_id'), ['investor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_startup_investor_matches_match_score'), ['match_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_startup_investor_matches_startup_id'), ['startup_id'], unique=False)

    op.create_table('startup_scores',
    sa.Column('startup_id', GUID(length=36), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=8, scale=2), nullable=False, comment='Overall computed score'),
    sa.Column('traction_score', sa.Numeric(precision=8, scale=2), nullable=True, comment='Score for traction category'),
    sa.Column('team_score', sa.Numeric(precision=8, scale=2), nullable=True, comment='Score for team category'),
    sa.Column('finance_score', sa.Numeric(precision=8, scale=2), nullable=True, comment='Score for finance category'),
    sa.Column('market_score', sa.Numeric(precision=8, scale=2), nullable=True, comment='Score for market category'),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Last time scores were recalculated'),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('startup_id', 'id')
    )
    with op.batch_alter_table('startup_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_startup_scores_last_updated_at'), ['last_updated_at'], unique=False)
        batch_op.create_index('ix_startup_scores_total', ['total_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_startup_scores_total_score'), ['total_score'], unique=False)
        batch_op.create_index('ix_startup_scores_updated', ['last_updated_at'], unique=False)

    op.create_table('calculation_audit_logs',
    sa.Column('assessment_id', GUID(length=36), nullable=False),
    sa.Column('calculation_step', sa.Enum('INPUT_VALIDATION', 'LOAD_CONFIG', 'RESOLVE_DEPENDENCIES', 'CALCULATE_KPI_SCORES', 'AGGREGATE_SUBCATEGORIES', 'AGGREGATE_CATEGORIES', 'CHECK_FATAL_FLAGS', 'CALCULATE_FINAL_SCORE', 'GENERATE_EXPLAINABILITY', name='calculationstep'), nullable=False),
    sa.Column('input_values', sa.JSON(), nullable=False, comment='Inputs to this calculation step'),
    sa.Column('output_values', sa.JSON(), nullable=False, comment='Outputs from this calculation step'),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False, comment='Performance profiling'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calculation_audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_assessment_step', ['assessment_id', 'calculation_step'], unique=False)
        batch_op.create_index(batch_op.f('ix_calculation_audit_logs_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calculation_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('evidence_uploads',
    sa.Column('assessment_id', GUID(length=36), nullable=False),
    sa.Column('kpi_id', sa.String(length=100), nullable=False, comment="KPI this evidence supports (e.g., 'fc_fulltime_founder')"),
    sa.Column('file_url', sa.String(length=500), nullable=False, comment='Storage path or S3 URL'),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False, comment='Manual/AI verification status'),
    sa.Column('verification_notes', sa.String(length=1000), nullable=True),
    sa.Column('decay_lambda', sa.Float(), nullable=False, comment='Time-decay rate: High volatility = 0.1, Low = 0.001'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_uploads', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_assessment_kpi', ['assessment_id', 'kpi_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_uploads_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('published_snapshots',
    sa.Column('assessment_id', GUID(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('score_band', sa.Enum('CRITICAL', 'POOR', 'FAIR', 'GOOD', 'EXCELLENT', name='scoreband'), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False, comment='Full explainability payload at time of snapshot'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False, comment='Should be 1st or 15th of month at midnight UTC'),
    sa.Column('framework_version', sa.String(length=20), nullable=False),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('published_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_published_snapshots_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_snapshots_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_snapshots_score'), ['score'], unique=False)
        batch_op.create_index('ix_snapshot_assessment_published', ['assessment_id', 'published_at'], unique=False)
        batch_op.create_index('ix_snapshot_published_at', ['published_at'], unique=False)

    op.create_table('startup_answers',
    sa.Column('startup_id', GUID(length=36), nullable=False),
    sa.Column('question_id', GUID(length=36), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True, comment='Used for text-type answers'),
    sa.Column('answer_number', sa.Numeric(precision=12, scale=2), nullable=True, comment='Used for number and boolean (0/1) answers'),
    sa.Column('selected_option_id', GUID(length=36), nullable=True, comment='Used for enum-type answers'),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['question_options.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('startup_id', 'question_id', name='uq_startup_question')
    )
    with op.batch_alter_table('startup_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_startup_answers_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_startup_answers_startup_id'), ['startup_id'], unique=False)
        batch_op.create_index('ix_startup_answers_startup_question', ['startup_id', 'question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('startup_answers', schema=None) as batch_op:
        batch_op.drop_index('ix_startup_answers_startup_question')
        batch_op.drop_index(batch_op.f('ix_startup_answers_startup_id'))
        batch_op.drop_index(batch_op.f('ix_startup_answers_question_id'))

    op.drop_table('startup_answers')
    with op.batch_alter_table('published_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshot_published_at')
        batch_op.drop_index('ix_snapshot_assessment_published')
        batch_op.drop_index(batch_op.f('ix_published_snapshots_score'))
        batch_op.drop_index(batch_op.f('ix_published_snapshots_published_at'))
        batch_op.drop_index(batch_op.f('ix_published_snapshots_assessment_id'))

    op.drop_table('published_snapshots')
    with op.batch_alter_table('evidence_uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_uploads_assessment_id'))
        batch_op.drop_index('ix_evidence_assessment_kpi')

    op.drop_table('evidence_uploads')
    with op.batch_alter_table('calculation_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calculation_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_calculation_audit_logs_assessment_id'))
        batch_op.drop_index('ix_audit_assessment_step')

    op.drop_table('calculation_audit_logs')
    with op.batch_alter_table('startup_scores', schema=None) as batch_op:
        batch_op.drop_index('ix_startup_scores_updated')
        batch_op.drop_index(batch_op.f('ix_startup_scores_total_score'))
        batch_op.drop_index('ix_startup_scores_total')
        batch_op.drop_index(batch_op.f('ix_startup_scores_last_updated_at'))

    op.drop_table('startup_scores')
    with op.batch_alter_table('startup_investor_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_startup_investor_matches_startup_id'))
        batch_op.drop_index(batch_op.f('ix_startup_investor_matches_match_score'))
        batch_op.drop_index(batch_op.f('ix_startup_investor_matches_investor_id'))
        batch_op.drop_index('ix_matches_startup_score')
        batch_op.drop_index('ix_matches_score')
        batch_op.drop_index('ix_matches_investor_score')

    op.drop_table('startup_investor_matches')
    with op.batch_alter_table('scoring_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scoring_rules_question_id'))

    op.drop_table('scoring_rules')
    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_options_question_id'))

    op.drop_table('question_options')
    with op.batch_alter_table('investor_preferences', schema=None) as batch_op:
        batch_op.drop_index('ix_investor_preferences_stage')
        batch_op.drop_index(batch_op.f('ix_investor_preferences_investor_id'))
        batch_op.drop_index('ix_investor_preferences_investor')
        batch_op.drop_index('ix_investor_preferences_industry')

    op.drop_table('investor_preferences')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_startup_id'))
        batch_op.drop_index(batch_op.f('ix_assessments_computed_score'))
        batch_op.drop_index('ix_assessment_startup_status')
        batch_op.drop_index('ix_assessment_score_band')

    op.drop_table('assessments')
    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_startups_user_id'))

    op.drop_table('startups')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_is_active'))
        batch_op.drop_index(batch_op.f('ix_questions_category'))

    op.drop_table('questions')
    with op.batch_alter_table('investors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investors_user_id'))

    op.drop_table('investors')
    with op.batch_alter_table('industries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_industries_name'))

    op.drop_table('industries')
    # ### end Alembic commands ###
